FROM golang:latest AS builder
WORKDIR /app
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o weather-app ./cmd/main.go

FROM alpine:latest
COPY --from=builder /app/weather-app /
CMD ["/weather-app"]